export const PROTECT_API_ERROR_LIMIT = 10;
export const API_RETRY_INTERVAL = 1500;
export const API_TIMEOUT = 3.5;
export const PROTECT_EVENTS_HEARTBEAT_INTERVAL = 10;
export const PROTECT_LOGIN_REFRESH_INTERVAL = 1800;
